FROM microsoft/dotnet:sdk AS build-env-titles
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY ./src ./
WORKDIR /app/tools/titlemigration
RUN dotnet restore

# Copy everything else and build
RUN dotnet publish -c Release -o out

# Build runtime image
FROM microsoft/dotnet:aspnetcore-runtime
WORKDIR /app
COPY --from=build-env-titles /app/tools/titlemigration/out .
ENTRYPOINT ["dotnet", "IMDBDegrees.Tools.TitleMigration.dll", "-i"]
