FROM microsoft/dotnet:sdk AS build-env-titles
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY ./src ./
WORKDIR /app/web/titles
RUN dotnet restore

# Copy everything else and build
RUN dotnet publish -c Release -o out

# Build runtime image
FROM microsoft/dotnet:aspnetcore-runtime
WORKDIR /app
COPY --from=build-env-titles /app/web/titles/out .
ENTRYPOINT ["dotnet", "IMDBDegrees.Web.Titles.dll"]
