FROM microsoft/dotnet:sdk AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY ./src ./
WORKDIR /app/tasks/mockBackgroundProcess1
RUN dotnet restore

# Copy everything else and build
RUN dotnet publish -c Release -o out

# Build runtime image
FROM microsoft/dotnet:aspnetcore-runtime
WORKDIR /app
COPY --from=build-env /app/tasks/mockBackgroundProcess1/out .
ENTRYPOINT ["dotnet", "mockBackgroundProcess1.dll"]

