FROM microsoft/dotnet:sdk AS build-env-actors
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY ./src ./
WORKDIR /app/web/actors
RUN dotnet restore

# Copy everything else and build
RUN dotnet publish -c Release -o out

# Build runtime image
FROM microsoft/dotnet:aspnetcore-runtime
WORKDIR /app
COPY --from=build-env-actors /app/web/actors/out .
ENTRYPOINT ["dotnet", "IMDBDegrees.Web.Actors.dll"]
